
INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
    VALUES ('Siwoo', 'Kim', '1989-03-04');

INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
  VALUES ('Eric', 'Clapton', '1945-03-30');

INSERT INTO SINGER(FIRST_NAME, LAST_NAME, BIRTH_DATE)
  VALUES ('John', 'Bulton', '1975-04-01');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
  VALUES (1, 'The Search For Everything', '2017-01-20');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (1, 'Battle Studies', '2009-11-17');

INSERT INTO ALBUM (SINGER_ID, TITLE, RELEASE_DATE)
VALUES (2, 'From the Cradle', '1994-09-13');

INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Guitar');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Piano');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Voice');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Drums');
INSERT INTO INSTRUMENT (INSTRUMENT_ID) VALUES ('Synthesizer');

INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (1, 'Guitar');
INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (1, 'Piano');
INSERT INTO SINGER_INSTRUMENT(SINGER_ID, INSTRUMENT_ID) VALUES (2, 'Guitar');
